### ISSUE TITLE
Fails to parse Google's Firerestore.proto

### ISSUE THREAD

**Issue by janvogt** [higherkindness/protobuf-parser-haskell#1]
First of all, thanks for publishing this library on hackage!

## Intro

I wanted to use it for a side project despite it's early stage. For now I had no success and will go a different route. Nevertheless, I wanted to let you know of the issues and provide my research. I suspect these problems to be relevant for quite a few more .proto files than my concrete example.

## Steps to reproduce

Try to parse [Google's firestore.proto](https://github.com/googleapis/googleapis/blob/2c28f646ca77b1d57550368be22aa388adde2e66/google/firestore/v1/firestore.proto).

E.g. by having the firestore.proto file in the same directory and running the following script:

```Haskell
#! /usr/bin/env runhaskell

module Main where

import Language.ProtocolBuffers.Parser (parseProtoBufFile)
import Text.Megaparsec.Error (errorBundlePretty, ShowErrorComponent(showErrorComponent))

instance ShowErrorComponent Char where
  showErrorComponent = show

main :: IO ()
main = parseProtoBufFile "firestore.proto" 
    >>= either (putStrLn . errorBundlePretty) print
```

## Expected result

A complete `ProtoBuf` AST of the .proto file.

## Actual result

Empty `ProtoBuf` AST

## Research

I figured out that the parser expects the `syntax = "proto3";` line to be before any comments. Changing this I was able to get a parse error instead of an empty AST. The first was
```
proto-deps.hs: user error (52:56:
   |
52 |       "https://www.googleapis.com/auth/cloud-platform,"
   |                                                        ^
unexpected newline
expecting ';'
)
```
wich is related to multiple lines in an assignment.

**Comment by serras** [comment]
Thanks for your report! I have uploaded a [new version](https://hackage.haskell.org/package/language-protobuf-1.0.1) to Hackage, which fixes these problems.

It turns out that `firestore.proto` uses features out of the spec. In particular the spec does not include objects as [constants](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#constant). However, since the goal is to parse as many `.proto` files as possible, I've added support for them too.

**Comment by janvogt** [comment]
Thanks for the new version with a fix. I expected something like that (out of spec), because your library looked pretty well done. I am going to try it again next time I will work with .proto files. Thanks again for improving Haskell support of protobufs!
